name: Build Python Application

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"

      - name: Install PyInstaller and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install altgraph==0.17.4 certifi==2024.2.2 charset-normalizer==3.3.2 idna==3.7 macholib==1.16.3 packaging==24.0 pillow==10.3.0 pyinstaller==6.6.0 pyinstaller-hooks-contrib==2024.5 setuptools==63.2.0 tqdm==4.66.4 urllib3==2.2.1

      - name: Build executable for Windows
        run: pyinstaller --onefile --noicon converter.py
        shell: cmd

      - name: Archive production artifacts for Windows
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/converter.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"

      - name: Install PyInstaller and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install altgraph==0.17.4 certifi==2024.2.2 charset-normalizer==3.3.2 idna==3.7 macholib==1.16.3 packaging==24.0 pillow==10.3.0 pyinstaller==6.6.0 pyinstaller-hooks-contrib==2024.5 setuptools==63.2.0 tqdm==4.66.4 urllib3==2.2.1

      - name: Build executable for Linux
        run: pyinstaller --onefile converter.py

      - name: Archive production artifacts for Linux
        uses: actions/upload-artifact@v2
        with:
          name: linux-executable
          path: dist/converter
